name: mpv-chat

default-extensions:
- DeriveGeneric
- LambdaCase
- OverloadedStrings
- ScopedTypeVariables
- TupleSections
- ViewPatterns

ghc-options:
- -Weverything
- -Wno-all-missed-specialisations
- -Wno-implicit-prelude
- -Wno-missing-deriving-strategies
- -Wno-missing-exported-signatures
- -Wno-missing-import-lists
- -Wno-missing-local-signatures
- -Wno-monomorphism-restriction
- -Wno-safe
- -Wno-unsafe

dependencies:
# === core ===
- base
- bytestring
- containers
- filepath
- stm
- text
- transformers
# === full ===
- async
- exceptions
- network-uri
- unordered-containers
# === extra ===
- aeson
- blaze-html
- conduit
- conduit-extra
- data-default-class
- http-conduit
- http-types
- megaparsec
- microlens
- microlens-th
- mime-types
- optparse-applicative
- scientific
- wai
- warp

library:
  source-dirs: src

executables:
  mpv-chat:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mpv-chat
