name: mpv-chat

default-extensions:
- DeriveGeneric
- LambdaCase
- OverloadedStrings
- ScopedTypeVariables
- TupleSections

ghc-options:
- -Weverything
- -Wno-all-missed-specialisations
- -Wno-implicit-prelude
- -Wno-missing-deriving-strategies
- -Wno-missing-exported-signatures
- -Wno-missing-import-lists
- -Wno-missing-local-signatures
- -Wno-monomorphism-restriction
- -Wno-safe
- -Wno-unsafe

dependencies:
# - directory
# - extra
# - mtl
# - process
# - resourcet
# - wai-app-static
# - wai-conduit
# - wai-extra
- aeson
- async
- base
- blaze-html
- bytestring
- conduit
- conduit-extra
- containers
- data-default
- exceptions
- filepath
- http-conduit
- http-types
- microlens
- microlens-th
- mime-types
- network
- scientific
- stm
- text
- transformers
- unordered-containers
- wai
- warp

library:
  source-dirs: src

executables:
  mpv-chat:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mpv-chat
