name: mpv-chat

default-extensions:
  - BlockArguments
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - EmptyCase
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - NoFieldSelectors
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables
  - Strict
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  # very noisy with LANGUAGE Strict
  - -Wno-redundant-bang-patterns
  - -Wno-safe
  - -Wno-unsafe
  # complains base is unused, even though we need it for hiding prelude
  - -Wno-unused-packages

dependencies:
  - name: base
    mixin:
      - hiding (Prelude)

library:
  source-dirs: src
  dependencies:
    # === core ===
    - bytestring
    - containers
    - filepath
    - mtl
    - stm
    - text
    - time
    - transformers
    # === full ===
    - exceptions
    - hashable
    - network-uri
    - unordered-containers
    # === extra ===
    - aeson
    - conduit
    - conduit-extra
    - data-default-class
    - http-media
    - http-types
    - lucid
    - mime-types
    - mono-traversable
    - optics-core
    - optics-th
    - scientific
    - sqlite-simple
    - unliftio
    - unliftio-core
    - wai
    - warp
  when:
    - condition: false
      other-modules: Paths_mpv_chat

executables:
  mpv-chat:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mpv-chat
      - optparse-applicative
    when:
      - condition: false
        other-modules: Paths_mpv_chat
